name: Lance File Write Read Round Trip Verification
on: [pull_request]

jobs:
  run:
    name: Lance File Write Read Round Trip Verification
    runs-on: "ubuntu-24.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install boto3
          pip install pyarrow
          pip install maturin

      - name: Download file from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LANCEDB_S3_READER_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LANCEDB_S3_READER_SECRET }}
        run: |
          python download_s3_file.py

      - name: List files
        run: ls -la

      - name: test lance write read round trip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LANCEDB_S3_READER_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LANCEDB_S3_READER_SECRET }}
        run: |
          python test_write_read.py
